/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNovoContatoRouteImport } from './routes/app.novo-contato'
import { Route as AppNovaRouteImport } from './routes/app.nova'
import { Route as AppIndicacoesRouteImport } from './routes/app.indicacoes'
import { Route as AppContatosRouteImport } from './routes/app.contatos'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNovoContatoRoute = AppNovoContatoRouteImport.update({
  id: '/novo-contato',
  path: '/novo-contato',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaRoute = AppNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicacoesRoute = AppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/nova': typeof AppNovaRoute
  '/app/novo-contato': typeof AppNovoContatoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/nova': typeof AppNovaRoute
  '/app/novo-contato': typeof AppNovoContatoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/contatos': typeof AppContatosRoute
  '/app/indicacoes': typeof AppIndicacoesRoute
  '/app/nova': typeof AppNovaRoute
  '/app/novo-contato': typeof AppNovoContatoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/contatos'
    | '/app/indicacoes'
    | '/app/nova'
    | '/app/novo-contato'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/contatos'
    | '/app/indicacoes'
    | '/app/nova'
    | '/app/novo-contato'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/analytics'
    | '/app/contatos'
    | '/app/indicacoes'
    | '/app/nova'
    | '/app/novo-contato'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/novo-contato': {
      id: '/app/novo-contato'
      path: '/novo-contato'
      fullPath: '/app/novo-contato'
      preLoaderRoute: typeof AppNovoContatoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova': {
      id: '/app/nova'
      path: '/nova'
      fullPath: '/app/nova'
      preLoaderRoute: typeof AppNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indicacoes': {
      id: '/app/indicacoes'
      path: '/indicacoes'
      fullPath: '/app/indicacoes'
      preLoaderRoute: typeof AppIndicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contatos': {
      id: '/app/contatos'
      path: '/contatos'
      fullPath: '/app/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppContatosRoute: typeof AppContatosRoute
  AppIndicacoesRoute: typeof AppIndicacoesRoute
  AppNovaRoute: typeof AppNovaRoute
  AppNovoContatoRoute: typeof AppNovoContatoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppContatosRoute: AppContatosRoute,
  AppIndicacoesRoute: AppIndicacoesRoute,
  AppNovaRoute: AppNovaRoute,
  AppNovoContatoRoute: AppNovoContatoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
